metallb:
  crds:
    enabled: true
  controller:
    enabled: true
  speaker:
    enabled: true
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.100-192.168.1.200
