apiVersion: v2
name: argocd
description: A Helm chart for Argo CD
type: application
version: 0.1.0
appVersion: "v3.0.12"
dependencies:
- name: argo-cd
  version: "8.2.5"
  repository: "https://argoproj.github.io/argo-helm"
